---
- name: MS SQL Installation
  hosts: all
  vars:
    source_path: /home/ansible/MSSQL_Ansible_Provisioning/
    dest_path: C:\Users\administrator\desktop\
    script_name: SQLServerInstallationv1.0.ps1
    ini_filename: MSSQL2012_StandAlone_64BIT.ini
    package_name: ntrights.exe
    setup_file: setup.exe
  tasks:
  - name: Copy PowerShell master Script
    win_copy:
      src: "{{ source_path +  script_name }}"
      dest: "{{ dest_path + script_name }}"
      force: yes
  - name: Copy INI file
    win_copy:
      src: "{{ source_path +  ini_filename }}"
      dest: "{{ dest_path + ini_filename }}"
      force: yes
  - name: Copy package file
    win_copy:
      src: "{{ source_path + package_name }}"
      dest: "{{ dest_path + package_name }}"
      force: yes
  - name: Copy package file
    win_copy:
      src: "{{ source_path + setup_file }}"
      dest: "{{ dest_path + setup_file }}"
      force: yes
  - name: Script Execution
    win_shell: "{{ dest_path + script_name }}"
