- name: test
  hosts: all
  tasks:

    - name: service status
      win_command: "powershell.exe (Get-Service |  where{ $_.name -like 'MSSQL*'} | select-object Name).Name.split('$') | select-string -NotMatch 'MSSQL' | select-string -NotMatch 'select-string -NotMatch 'MSSQL''"
      register: check_service
    - name: setfact
      set_fact:
        listservice: "{{ check_service.stdout_lines | map('trim') |  select('match', '^([a-zA-Z])+')|  list  }}"
#    - name: loops
#      win_service:
#        name: "{{ item }}"
#        state: "stopped"
    - debug:
       # msg: "{{ item.split(\"MSSQL$\") }}"
        msg: "{{ item }}"
      with_items: "{{ listsrv }}"
