#- name: Configuration for Route53
- local_action:
    module: elb_application_lb_facts
    region: "{{ demo_region }}"
    names: "{{ elb_name }}"
  register: elb_facts

- name: debug elb facts
  debug:   
    msg: "{{ elb_facts.load_balancers[0].canonical_hosted_zone_id }}"

- name: Add an alias record that points to an Amazon ELB
  route53:
    state: present
    zone: "{{ zone_name }}"
    record: "{{ host_name }}.{{ zone_name }}"
    type: A
    value: "{{ elb_facts.load_balancers[0].dns_name }}"
    alias: True
    alias_hosted_zone_id: "{{ elb_facts.load_balancers[0].canonical_hosted_zone_id }}"

- name: Mail the URL
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: "{{ mailid }}"
    subject: PostgreSQL DB Details
    body: Application hosted link:- "{{ host_name }}.{{ zone_name }}"
