---
- win_copy:
    src: files/precheck.ps1
    dest: C:/pre_post/precheck.ps1

- win_copy:
    src: files/postcheck.ps1
    dest: C:/pre_post/postcheck.ps1

- name: Excute Scripts
  win_command: powershell.exe C:/pre_post/precheck.ps1

- fetch:
    src: C:\pre_post\pre_patch_report.html
    dest: reports/pre_patch_report.html
    flat: yes

- name: service status
  win_command: "powershell.exe Get-Service |  where{ $_.name -like 'MSSQL*'} |select-object Status"
  register: check_ser
    
- mail:
    host: smtp.gmail.com
    port: 587
    secure: starttls
    charset: utf-8
    sender: prajwalgl28@gmail.com
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: 'simranjeet.g.singh@accenture.com'
    subject: MSSQL Service Status
    body: System {{ ansible_hostname }} has MSSQL database is running condition, shutting them down before patching. 
  delegate_to: localhost      
  when: '"Running" in check_ser.stdout'

- name: setup
  win_disk_facts:
  register: pro

- name: free space percentage
  debug:
    msg: "{{ (pro.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining /  pro.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size *100)|int }}"
  register: d_perc

- mail:
    host: smtp.gmail.com
    port: 587
    secure: starttls
    charset: utf-8
    sender: prajwalgl28@gmail.com
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: 'simranjeet.g.singh@accenture.com'
    subject: MSSQL Service Status
    body: System {{ ansible_hostname }} drive utilized over 80 Percent.
  delegate_to: localhost
  when: d_perc.msg|int > 80

- meta: end_play
  when: d_perc.msg|int > 80
###########backup pre

- win_copy:
    src: /home/ansible/patching_mssql/MSSQL_Ansible_Patching/win_mssql_patch/files/SQLdiscovery.ps1
    dest: C:/pre_post/SQLdiscovery.ps1
- name: Execute Scripts
  win_command: powershell.exe C:/pre_post/SQLdiscovery.ps1
- name:
  win_command: "powershell.exe get-content 'C:/mdffiles.txt'"
  register: backup_files
- name: setfact
  set_fact:
    listpath: "{{ backup_files.stdout_lines | map('trim') | list  }}"
#####
- name: service status on mssql
  win_command: "powershell.exe Get-Service |  where{ $_.name -like 'MSSQL*'} | select-object Name"
  register: check_ser
- name: setfact mssql list
  set_fact:
    listsrv: "{{ check_ser.stdout_lines | map('trim')| select('match', '^(MSSQL)+') | list  }}"
- name: stopping mssql databases instances
  win_service:
    name: "{{ item }}"
    state: "stopped"
  with_items: "{{ listsrv }}"
####backup###
- name: loops backup
  win_command: powershell.exe copy-item "{{ '\"' + item + '\"' }}" C:\\pre_post
  with_items: "{{ listpath }}"

###

- import_tasks: patching.yml


- name: Execute the Post Script
  win_command: powershell.exe C:/pre_post/postcheck.ps1 

- fetch:
    src: C:/pre_post/post_patch_report.html
    dest: reports/post_patch_report.html
    flat: yes
  
- mail:
    host: smtp.gmail.com
    port: 587
    secure: starttls
    charset: utf-8
    sender: prajwalgl28@gmail.com
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: 'simranjeet.g.singh@accenture.com'
    subject: Pre and Post Check Reports
    attach:
      - reports/post_patch_report.html
      - reports/pre_patch_report.html
  delegate_to: localhost

