- name: test
  hosts: all
  vars:
    - version: "postgresql10-server-10.3-2.8"
  tasks:
  - name: contrib
    set_fact:
      contribpack: "{{ version | regex_replace('server','contrib')}}"
  - debug:
      msg: "{{ contribpack }}"
