- name: test
  hosts: all
  vars:
    - dbname: killerdb
    - appuser: killeruser
    - apppassword: Password@123
    - appport: 5432
  tasks:
  - pip: name=psycopg2
  - postgresql_user:
      name: "{{ appuser }}"
      password: "{{ apppassword }}"
      state: present

  - name: CREATE POSTGRES DATABASE
    postgresql_db:
      name: "{{ dbname }}"
      port: "{{ appport }}"
      owner: "{{ appuser }}"
      state: present
    register: dbcreate

  - debug: msg="{{ dbcreate }}"

  - name: entry in pg_hba.conf
    shell: echo "host    {{ dbname }}          {{ appuser }}         0.0.0.0/0                 md5" >> /var/lib/pgsql/data/pg_hba.conf
    when: dbcreate.changed == true

  - name: entry for listener
    shell: echo "listen_addresses = '*'" >> /var/lib/pgsql/data/postgresql.conf
    when: dbcreate.changed == true

  - name: postgres service start
    service:
      name: postgresql
      state: restarted
    become_user: root
