- name: check SQL the folder in C
  win_file:
    path: C:\sql
    state: absent

- name: getting the details
  setup:
    filter: ansible_default_ipv4.address
  register: p
- name: getting the available disk space details
  win_disk_facts:
  register: disk
- name: getting the available service details
  win_service:
    name: "{{ 'SQL Server ('+ sql_instance_name + ')' }}"
  register: services
#- name: Include task list in play only if the condition is true for 2014 installtion
#  include: install_mssql_2014.yml
#  when:
#    - mssql_version == 2014
#    - p.ansible_facts.ansible_processor_count|int >= 1
#    - p.ansible_facts.ansible_memtotal_mb|int >= 1024
#    - p.ansible_facts.ansible_distribution == "Microsoft Windows Server 2016 Datacenter"
#    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int >= 6442450944
#    - not services.exists

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Processor less than 1 on the server"
  delegate_to: localhost
  when:
    - mssql_version == 2014 
    - p.ansible_facts.ansible_processor_count|int < 1

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Memory Available less than 1GB on the server"
  delegate_to: localhost
  when:
    - mssql_version == 2014
    - p.ansible_facts.ansible_memtotal_mb|int < 1024

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Not compatible with windows OS provided"
  delegate_to: localhost
  when:
    - mssql_version == 2014
    - p.ansible_facts.ansible_distribution != "Microsoft Windows Server 2016 Datacenter"

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Space not enough on OS"
  delegate_to: localhost
  when:
    - mssql_version == 2014
    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int < 6442450944

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Database Instance already Installed"
  delegate_to: localhost
  when:
    - mssql_version == 2014
    - services.exists

- name: Include task list in play only if the condition is true for 2014 installtion
  include: install_mssql_2014.yml
  when:
    - mssql_version == 2014
    - p.ansible_facts.ansible_processor_count|int >= 1
    - p.ansible_facts.ansible_memtotal_mb|int >= 1024
    - p.ansible_facts.ansible_distribution == "Microsoft Windows Server 2016 Datacenter"
    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int >= 6442450944
    - not services.exists

######################


#- name: Include task list in play only if the condition is true for 2012 installtion
#  include: install_mssql_2012.yml
#  when:
#    - mssql_version == 2012
#    - p.ansible_facts.ansible_processor_count|int >= 1
#    - p.ansible_facts.ansible_memtotal_mb|int >= 512
#    - p.ansible_facts.ansible_distribution == "Microsoft Windows Server 2016 Datacenter"
#    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int >= 6442450944
#    - not services.exists

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Processor less than 1 on the server"
  delegate_to: localhost
  when:
    - mssql_version == 2012
    - p.ansible_facts.ansible_processor_count|int < 1

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Memory Available less than 1GB on the server"
  delegate_to: localhost
  when:
    - mssql_version == 2012
    - p.ansible_facts.ansible_memtotal_mb|int < 1024

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Not compatible with windows OS provided"
  delegate_to: localhost
  when:
    - mssql_version == 2012
    - p.ansible_facts.ansible_distribution != "Microsoft Windows Server 2016 Datacenter"

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Space not enough on OS"
  delegate_to: localhost
  when:
    - mssql_version == 2012
    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int < 6442450944

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Database Instance already Installed"
  delegate_to: localhost
  when:
    - mssql_version == 2012
    - services.exists

- name: Include task list in play only if the condition is true for 2012 installtion
  include: install_mssql_2012.yml
  when:
    - mssql_version == 2012
    - p.ansible_facts.ansible_processor_count|int >= 1
    - p.ansible_facts.ansible_memtotal_mb|int >= 512
    - p.ansible_facts.ansible_distribution == "Microsoft Windows Server 2016 Datacenter"
    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int >= 6442450944
    - not services.exists

#########################

#- name: Include task list in play only if the condition is true for 2008 installtion
#  include: install_mssql_2008.yml
#  when:
#    - mssql_version == 2008
#    - p.ansible_facts.ansible_processor_count|int >= 1
#    - p.ansible_facts.ansible_memtotal_mb|int >= 512
#    - p.ansible_facts.ansible_distribution == "Microsoft Windows Server 2016 Datacenter"
#    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int >= 6442450944
#    - not services.exists

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Processor less than 1 on the server"
  delegate_to: localhost
  when:
    - mssql_version == 2008
    - p.ansible_facts.ansible_processor_count|int < 1

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Memory Available less than 1GB on the server"
  delegate_to: localhost
  when:
    - mssql_version == 2008
    - p.ansible_facts.ansible_memtotal_mb|int < 1024

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Not compatible with windows OS provided"
  delegate_to: localhost
  when:
    - mssql_version == 2008
    - p.ansible_facts.ansible_distribution != "Microsoft Windows Server 2016 Datacenter"

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Space not enough on OS"
  delegate_to: localhost
  when:
    - mssql_version == 2008
    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int < 6442450944

- name: Mail Notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: janpreet27july5@gmail.com
    password: Globe@123
    to: simranjeet.g.singh@accenture.com
    subject: MSSQL Installation {{ ansible_hostname }}
    body: "System {{ ansible_hostname }},Database not installed, Database Instance already Installed"
  delegate_to: localhost
  when:
    - mssql_version == 2008
    - services.exists

- name: Include task list in play only if the condition is true for 2008 installtion
  include: install_mssql_2008.yml
  when:
    - mssql_version == 2008
    - p.ansible_facts.ansible_processor_count|int >= 1
    - p.ansible_facts.ansible_memtotal_mb|int >= 512
    - p.ansible_facts.ansible_distribution == "Microsoft Windows Server 2016 Datacenter"
    - disk.ansible_facts.ansible_disks[0].partitions[0].volumes[0].size_remaining|int >= 6442450944
    - not services.exists

